all: diskinfo diskget disklist diskput

diskinfo: diskinfo.cpp
	g++ -Wall diskinfo.cpp  -o diskinfo

diskget: diskget.cpp
	g++ -Wall diskget.cpp  -o diskget

disklist: disklist.cpp
	g++ -Wall disklist.cpp  -o disklist

diskput: diskput.cpp
	g++ -Wall diskput.cpp  -o diskput
